### ISSUE TITLE
Clarify how CircuitBreaker.failOn() should work

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-fault-tolerance#240] opened 2018-04-04 11:33 UTC
There is no mention in the spec text and the javadoc is rather unsatisfactory: _"Define the failure criteria"_.  The original intent was probably to only use the circuit breaker if the exception thrown is assignable to any of the listed exceptions?

**Comment by mkouba** [comment] 2018-04-04 11:40
Also what happens if `@CircuitBreaker` is used together with `@Fallback`? E.g. if the failure does not match `failOn()` should be the fallback used?

**Comment by Azquelt** [comment] 2018-12-20 14:48
Expected behaviour: when the method throws an exception, if failOn includes that exception, then the execution is counted by the circuitBreaker as a failure, otherwise it is counted as a success.

`@Fallback` is unaffected by the circuit breaker, if an exception is thrown then the fallback logic will be invoken, even if the circuit breaker did not consider the exception a failure.

We need a spec to better define the behaviour of `failOn` and a TCK for using `@Fallback` with `@CircuitBreaker`

**Comment by mkouba** [comment] 2018-12-20 15:06
> if failOn includes that exception

Really? I think that _"if the exception thrown is assignable to any of the listed exceptions"_ would be a little bit more useful.

> @Fallback is unaffected by the circuit breaker

Hm, the spec is clear that: _"Fallbacks are invoked once a Retry or CircuitBreaker has failed enough times."_. So if this should mean _"a fallback is invoked whenever the method invocation fails"_ then this part of the spec would really deserve rewording.

**Comment by Azquelt** [comment] 2018-12-20 16:12
> I think that "if the exception thrown is assignable to any of the listed exceptions" would be a little bit more useful.

Yeah sorry, that's what I meant but your phrasing is much more precise

> if this should mean "a fallback is invoked whenever the method invocation fails" then this part of the spec would really deserve rewording.

The spec has since been updated, though it's still not totally clear about what causes the fallback to be invoked. The version in the master branch now reads
> Fallback annotation can be used on its own or together with other Fault Tolerance annotations.

**Closed** 2019-01-09 14:56 UTC
