### ISSUE TITLE
Avoid the use of ChronoUnit

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-fault-tolerance#49] opened 2017-07-02 02:25 UTC
The usage of ChronoUnit has to do with specific dates and times.  Since we're dealing with operations, we should be using TimeUnit.

**Comment by Emily-Jiang** [comment] 2017-07-05 14:21
ChronoUnit is similar to the TimeUnit and can easily converted to a Duration. ChronoUnit, part of Java8, will be the new popular thing.  In my view, we should use the new java.time package classes if possible.

**Comment by johnament** [comment] 2017-07-06 02:39
java.time is not designed for concurrency operations.  TimeUnit is from the concurrency package.  I'm confused by your claim "will be the new popular thing"

In addition, the Java 8 javadocs make this claim about chrono:

> The java.time.chrono package contains the calendar neutral API ChronoLocalDate, ChronoLocalDateTime, ChronoZonedDateTime and Era. This is intended for use by applications that need to use localized calendars. It is recommended that applications use the ISO-8601 date and time classes from this package across system boundaries, such as to the database or across the network. The calendar neutral API should be reserved for interactions with users.

So I'm not convinced we want to use ChronoUnit in our APIs.  There's a bug open, and apparently conversion support between the two will be added in [JDK 9](https://bugs.openjdk.java.net/browse/JDK-8141452)

**Comment by Emily-Jiang** [comment] 2017-07-09 22:19
John, thanks for the more info! As we plan to add some apis/spis in the future, it is natural fit to convert the ChronoUnit to Duration. I am thinking all of the current ChronoUnit will be converted to Duration in the apis/spis version. It is difficult to convert from TimeUnit to Duration. Thoughts?

**Comment by tevans78** [comment] 2017-07-12 11:01
Most of the places where a length of time is required, it's not related to concurrency. e.g. a retry delay. From the user's perspective, adding @Timeout does not introduce any concurrency to their code (even if we are forced to implement it that way).

If the requirement is for a length of time, then java.time.Duration is the correct choice. The only reason we can't use Duration directly is because Java doesn't allow complex types for Annotation values. A combination of a long and java.time.temporal.ChronoUnit is the next best thing, allowing easy conversion to Duration.

**Comment by Emily-Jiang** [comment] 2017-07-17 22:02
I plan to close this issue. Please comment if you feel otherwise.

**Comment by Emily-Jiang** [comment] 2017-07-27 10:24
I'm closing this based on our conversation. @johnament are you ok with it?

**Closed** 2017-08-15 15:35 UTC

**Comment by McFoggy** [comment] 2017-10-12 20:12
Even if the issue is closed, I'd like to raise my voice to say that I agree with @johnament ; TimeUnit looks better suited than ChronoUnit here.
Unless I have totally missed the usage of ChronoUnit, one need some instance of Temporal, meaning the creation of probably java.time.Instant and java.time.Clock.
Aren't the java.util.concurrent.TimeUnit enums answering the need in by far more efficient way?

With ChronoUnit, if I want to compute a delay, I will have to query a clock for an initial Instant to which I will add the ChronoUnit and then compute a Duration between both.

With ChronoUnit returned by Timeout.unit()
```java
Timeout t = retrieveTimeout();

Instant now = Instant.now();
Instant end = t.unit().addTo(now, t.value());
long millis = Duration.between(now, end).toMillis();
```

With TimeUnit returned by Timeout.unit()
```
long millis = t.unit().toMillis(t.value())
```

Looks much more simple and is based on simple math, no unnecessary object creation.

**Comment by Emily-Jiang** [comment] 2017-10-13 09:09
What you should do is the following. 

`long millis = Duration.of(t.value(), t.unit()).toMillis();`

**Comment by McFoggy** [comment] 2017-10-13 17:17
Thanks for the hint.
