### ISSUE TITLE
TCK uses currentTimeMillis

### ISSUE THREAD

**Issue by benjamin-confino** [eclipse/microprofile-fault-tolerance#373] opened 2018-12-17 10:25 UTC
A couple of TCK tests still use `System.currentTimeMillis()` for measuring the time a thread takes. It is recommended that `nanoTime()` is used instead as nanoTime is independent of the system clock and, for example, switching to daylight savings time will not affect the tests.

**Comment by Emily-Jiang** [comment] 2018-12-18 16:24
fixed by #374

**Comment by Azquelt** [comment] 2019-01-03 16:53
In some cases, `currentTimeMillis()` was replaced with `nanoTime()` without changing the value which it is compared against, making the expected time a million times shorter than was intended.

**Closed** 2019-01-07 22:47 UTC
