### ISSUE TITLE
@ShouldThrowException with testable=true change breaks TCK on OpenLiberty 

### ISSUE THREAD

**Issue by neilgsyoung** [eclipse/microprofile-fault-tolerance#211] opened 2018-01-03 13:56 UTC
Opening an issue to track this problem. 

There is a problem with the change introduced under issue #203. I cannot get the change to run on a managed arquillian OpenLiberty container. When I originally tested the change in 
#203 I think I'd built fault tolerance against Arquillian 1.1.14 but had run against Arquillian 1.1.12.
Having built my environment more carefully against Arquillian 1.1.14 I see (for example)...

test(org.eclipse.microprofile.fault.tolerance.tck.invalidParameters.InvalidRetryMaxRetriesTest) Time elapsed: 0.015 sec <<< FAILURE!
java.lang.NullPointerException: null
at org.jboss.arquillian.protocol.servlet.BaseServletProtocol.getExecutor(BaseServletProtocol.java:56)
at org.jboss.arquillian.protocol.servlet.BaseServletProtocol.getExecutor(BaseServletProtocol.java:33)
at org.jboss.arquillian.container.test.impl.execution.RemoteTestExecuter.getContainerMethodExecutor(RemoteTestExecuter.java:112)
at org.jboss.arquillian.container.test.impl.execution.RemoteTestExecuter.execute(RemoteTestExecuter.java:102)

... I saw that that an issue was opened against Firefly wildfly/wildfly-arquillian#116 this may be equivalent.

**Comment by neilgsyoung** [comment] 2018-01-04 16:45
My understanding is this. Our OpenLiberty TCK test environment uses a managed Liberty (wlp) Arquillian container. So 2 JVMs are in operation.
The first JVM is where the Arquillian core code and wlp Arquillian Container code are run. So this JVM is responsible for starting the 
Liberty Server in the other JVM (if it hasn't already started), installing war files in the Server's "dropins" directory from which they 
are automatically started, and driving the tests against the apps installed in the Liberty Server. This first JVM (via the wlp container code) 
will inspect the Liberty Server's output messages log to see if any exceptions have been reported. If they have then, the the wlp Arquillian
container will throw an "appropriate" exception which will then be handled by the Arquillian core.

When I run a single failing TCK test with arquillian debug enabled, I see this...

(E) ManagerStarted
        (O) ConfigurationRegistrar.loadConfiguration
        (E) ArquillianDescriptorImpl
                (O) ProtocolRegistryCreator.createRegistry
                (E) ProtocolRegistry
                (O) ContainerRegistryCreator.createRegistry
                (E) LocalContainerRegistry
(E) BeforeSuite
        (I) TestContextHandler.createSuiteContext
        (O) ContainerEventController.execute
        (E) SetupContainers
                (O) ContainerLifecycleController.setupContainers
                (E) SetupContainer
                        (I) ContainerDeploymentContextHandler.createContainerContext
                        (O) ContainerLifecycleController.setupContainer
                        (E) BeforeSetup
                        (E) ContainerImpl
                        (E) AfterSetup
                (O) ClientDeployerCreator.createClientSideDeployer
                (E) ClientDeployer
                (O) ClientContainerControllerCreator.createClientSideContainerController
                (E) ClientContainerController
        (E) StartSuiteContainers
                (O) ContainerLifecycleController.startSuiteContainers
                (E) StartContainer
                        (I) ContainerDeploymentContextHandler.createContainerContext
                        (O) ContainerLifecycleController.startContainer
                        (E) BeforeStart
>>HERE the Liberty Server is reported to have successfully started
                        (E) AfterStart
(E) BeforeClass
        (I) TestContextHandler.createSuiteContext
        (I) TestContextHandler.createClassContext
        (E) TestClass
        (O) ContainerRestarter.restart
        (O) ContainerEventController.execute
        (E) StartClassContainers
                (O) ContainerLifecycleController.startClassContainers
        (E) GenerateDeployment
                (O) DeploymentGenerator.generateDeployment
                (E) DeploymentScenario
        (E) DeployManagedDeployments
                (O) ContainerDeployController.deployManaged
                (E) DeployDeployment
                        (I) DeploymentExceptionHandler.verifyExpectedExceptionDuringDeploy
                        (I) ContainerDeploymentContextHandler.createContainerContext
                        (I) ContainerDeploymentContextHandler.createDeploymentContext
                        (O) ContainerDeployController.deploy
                        (E) DeploymentDescription
                        (E) Deployment
                        (E) BeforeDeploy
                                (O) ArchiveDeploymentExporter.callback
                                (O) ArchiveDeploymentToolingExporter.export
>> HERE we call the wlp-managed-container deploy() method
>> HERE we checkForDeployExceptions
############DEBUG found CWWKZ0002E for application: ftInvalidRetry2
[03/01/18 17:11:21:982 GMT] 00000029 com.ibm.ws.app.manager.AppMessageHelper                      E CWWKZ0002E: An exception occurred while starting the application ftInvalidRetry2. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DefinitionException: CWMFT5010E: The Retry policy parameter maxRetries value -3 for org.eclipse.microprofile.fault.tolerance.tck.invalidParameters.RetryClientForValidationMaxRetries.serviceA is not valid because it must be greater than or equal to -1.
>> HERE wlp-managed-container found a org.jboss.weld.exceptions.DefinitionException, throw a javax.enterprise.inject.spi.DefinitionException to Arquillian core.
                        (E) DefinitionException
        (O) ClientBeforeAfterLifecycleEventExecuter.on
(E) Before
        (I) TestContextHandler.createSuiteContext
        (I) TestContextHandler.createClassContext
        (E) TestClass
        (I) TestContextHandler.createTestContext
        (I) ContainerEventController.createBeforeContext
        (O) TestInstanceEnricher.enrich
        (O) ClientBeforeAfterLifecycleEventExecuter.on
(E) Test
        (I) TestContextHandler.createSuiteContext
        (I) TestContextHandler.createClassContext
        (E) TestClass
        (I) TestContextHandler.createTestContext
        (I) ContainerEventController.createTestContext
        (O) ClientTestExecuter.execute
        (E) RemoteExecutionEvent
                (O) RemoteTestExecuter.execute
>> HERE is the NPE!!!!!!!!!!!!!!
                (E) NullPointerException
                (E) NullPointerException
        (E) NullPointerException
        (E) NullPointerException
(E) After
        (I) TestContextHandler.createSuiteContext
        (I) TestContextHandler.createClassContext
        (E) TestClass
        (I) TestContextHandler.createTestContext
        (I) UpdateTestResultBeforeAfter.update
Jan 03, 2018 5:11:39 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 2 (of type TestResult) for org.jboss.arquillian.testng.extension.UpdateTestResultBeforeAfter#update is null. Observer method won't be invoked.
(E) AfterClass
        (I) TestContextHandler.createSuiteContext
        (I) TestContextHandler.createClassContext
        (E) TestClass
        (O) ClientBeforeAfterLifecycleEventExecuter.on
        (O) ContainerEventController.execute
        (E) UnDeployManagedDeployments
                (O) ContainerDeployController.undeployManaged
                (E) UnDeployDeployment
                        (I) ContainerDeploymentContextHandler.createContainerContext
                        (I) ContainerDeploymentContextHandler.createDeploymentContext
                        (O) ContainerDeployController.undeploy
                        (E) BeforeUnDeploy
> waitForApplicationTargetState
                        (E) AfterUnDeploy
        (E) StopManualContainers
                (O) ContainerLifecycleController.stopManualContainers
        (E) StopClassContainers
                (O) ContainerLifecycleController.stopClassContainers
(E) AfterSuite
        (I) TestContextHandler.createSuiteContext
        (O) ContainerEventController.execute
        (E) StopSuiteContainers
                (O) ContainerLifecycleController.stopSuiteContainers
                (E) StopContainer
                        (I) ContainerDeploymentContextHandler.createContainerContext
                        (O) ContainerLifecycleController.stopContainer
                        (E) BeforeStop
                        (E) AfterStop
(E) ManagerStopping
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 30.12 sec <<< FAILURE! - in TestSuite
test(org.eclipse.microprofile.fault.tolerance.tck.invalidParameters.InvalidRetryMaxRetriesTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.NullPointerException: null
        at org.jboss.arquillian.protocol.servlet.BaseServletProtocol.getExecutor(BaseServletProtocol.java:56)
        at org.jboss.arquillian.protocol.servlet.BaseServletProtocol.getExecutor(BaseServletProtocol.java:33)
        at org.jboss.arquillian.container.test.impl.execution.RemoteTestExecuter.getContainerMethodExecutor(RemoteTestExecuter.java:112)

**Comment by Emily-Jiang** [comment] 2018-01-31 14:21
@carlos can you see whether you can help us?

**Comment by carlosdlr** [comment] 2018-01-31 14:25
I'll check

**Comment by carlosdlr** [comment] 2018-02-07 17:22
1

**Comment by neilgsyoung** [comment] 2018-03-12 10:27
Carlos and I messaged about this. I think this issue is most likely specific to our OpenLiberty environment. It looks like an issue with the Liberty version of the Arquillian Container. We are actively investigating.

**Comment by carlosdlr** [comment] 2018-03-14 18:32
Hello @neilgsyoung 

Check this change that was made it in microprofile tck project the arquilian version was changed
https://github.com/eclipse/microprofile-fault-tolerance/pull/203/commits/62748bc36f1df057359776d465ab48a760b94efe
and maybe is necessary made the same on liberty code.

**Comment by neilgsyoung** [comment] 2018-03-15 09:09
Thanks @carlosdlr  we're needing to make a number of OpenLiberty Arquillian container changes, I'll double check that we have the version changes in our pom.xmls.

**Comment by Emily-Jiang** [comment] 2018-03-21 14:29
@hutchig pls retest against the current latest arquillian container to see whether this is still the case?

**Comment by hutchig** [comment] 2018-04-18 13:42
I refreshed my local arquillian container to the current master
(date of HEAD commit in version below) and uploaded it to
artifactory. 

<dependency>
    <groupId>com.ibm.ws.org.jboss.arquillian.container</groupId>
    <artifactId>arquillian-liberty-managed</artifactId>
    <version>999.0.20180329212918</version>
    <type>pom</type>
</dependency>

I edited https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/pom.xml
to reference this and the 1.1 FT TCK (which I had done a mvn clean install on to
insert into my local repository. 

This gave me the following results for the ShouldThrow tests:
(will update)/

**Comment by hutchig** [comment] 2018-04-18 14:15
These all pass: 
```
Name | Tests | Errors | Failures | Skipped | Time(s) | Time Stamp | Host
-- | -- | -- | -- | -- | -- | -- | --
IncompatibleFallbackMethodTest | 1 | 0 | 0 |   | 0.002 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
IncompatibleFallbackMethodWithArgsTest | 1 | 0 | 0 |   | 0.000 | 18 Apr 2018 13:48:22 GMT | gordons-mbp.hursley.uk.ibm.com
IncompatibleFallbackPolicies | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
IncompatibleFallbackTest | 1 | 0 | 0 |   | 0.000 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com


Name | Tests | Errors | Failures | Skipped | Time(s) | Time Stamp | Host
-- | -- | -- | -- | -- | -- | -- | --
InvalidBulkheadAsynchQueueTest | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidBulkheadValueTest | 1 | 0 | 0 |   | 0.002 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidCircuitBreakerDelayTest | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidCircuitBreakerFailureRatioNegTest | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidCircuitBreakerFailureRatioPosTest | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidCircuitBreakerFailureReqVol0Test | 1 | 0 | 0 |   | 0.002 | 18 Apr 2018 13:48:22 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidCircuitBreakerFailureReqVolNegTest | 1 | 0 | 0 |   | 0.002 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidCircuitBreakerFailureSuccess0Test | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidCircuitBreakerFailureSuccessNegTest | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidRetryDelayDurationTest | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidRetryDelayTest | 1 | 0 | 0 |   | 0.014 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidRetryJitterTest | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidRetryMaxRetriesTest | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:22 GMT | gordons-mbp.hursley.uk.ibm.com
InvalidTimeoutValueTest | 1 | 0 | 0 |   | 0.001 | 18 Apr 2018 13:48:21 GMT | gordons-mbp.hursley.uk.ibm.com

```

**Comment by hutchig** [comment] 2018-04-18 14:17
So this issue is not present with the updated Liberty Arquillian Container.

**Comment by carlosdlr** [comment] 2018-04-18 14:26
Thank you

**Comment by Azquelt** [comment] 2018-05-10 13:54
Need to re-open this, the issue is not fixed. 

We were still using arquillian 1.1.13 when we ran the tests when we saw the tests passing. At this version, the `testable = true` flag is ignored because it wasn't implemented yet.

@carlosdlr Can you provide a bit more information about how this is supposed to work?

As far as I can see, setting `testable = true` on a deployment means that the test class is supposed be added to the deployment and that once the deployment is running, arquillian will call across to the deployed app and run the tests on the server.

However, when `@ShouldThrowException` is used, an exception is expected during the deployment that causes the app not to start. If the app doesn't start, there's no way to run the test on the server, so how can the test ever pass?

Furthermore, looking at the stack trace and the Arquillian code, the NPE appears to be caused by the `ProtocolMetaData` being `null`. The OpenLiberty arquillian container works by providing an implementation of the `DeployableContainer` interface. `DeployableContainer.deploy()` is supposed to return the `ProtocolMetaData`, but it's also the method that's supposed to throw the exception expected by `@ShouldThrowException`! How is this method supposed to both provide the required `ProtocolMetaData` while also throwing the expected expected exception?

What am I missing here?

**Comment by Azquelt** [comment] 2018-05-10 17:06
If your container or test runner needs to modify the archive before deployment, could they do this by registering as a `BeforeDeploy` observer rather than an `ApplicationArchiveProcessor`? (Testing locally, I seem to be able to add a file to a non-testable archive this way)

**Comment by hutchig** [comment] 2018-05-14 12:07
The current wildfly relevant link is https://issues.jboss.org/browse/WFARQ-36

**Comment by hutchig** [comment] 2018-05-14 13:07
The exception that Liberty and Wildfly see is at: 

org.jboss.arquillian.protocol.servlet.BaseServletProtocol.getExecutor(BaseServleetProtocol.java:56).
The line is that is NPE is:
```
public ServletMethodExecutor getExecutor(ServletProtocolConfiguration protocolConfiguration,
ProtocolMetaData metaData, CommandCallback callback) {
Collection<HTTPContext> contexts = metaData.getContexts(HTTPContext.class);
```

due to the metaData being null.

...but the metadata is supposed to be returned from the same container deploy() method
that is being specced to return an exception:

```
@Override
public ProtocolMetaData deploy(final Archive<?> archive) throws DeploymentException
{
```
This is the implementation of the common (cross vendor/container) abstract interface:
DeployableContainer. 

Nor do not think it is logically possible that the 'fix' for this can be in each
vendors container code as it is impossible for the container to both return the metadata
AND raise an exception and...there is no other method in the interface that can be used
to get the required metadata to make the test testable.

So the only viable fix is for the arquillian-core caller of deploy to deal better with an unset metadata if the deploy method raises an exception. However the code is being driven down the problem codepath by the
testable=true parameter. There is no other method in DeployableContainer interface for the core
to communicate with the container and get a ProtocolMetaData - thus the only logical conclusion
is that the core cannot have access to the metadata when the deployment is specced to
throw an Exception - so the test can never be "testable" for container implementations it is
impossible given the arquillian-core/container interface as it is.

The core uses, and can only use, the metadata to get the Context endpoints to drive the test. If the NPE was fixed it would just later on raise:

(arquillian-core code)
```
if (contexts.size() == 0) {
throw new IllegalArgumentException(
```
Thus Arquillian ShouldThrowException(... testable=true) is a logical inconsistency and invalid test assertion given the current Arquillian core<->container interfaces. The Annotation itself
is from Arquillian org.jboss.arquillian.container.test.api but I do not see a logical path for
https://github.com/eclipse/microprofile-fault-tolerance/pull/203 to be honoured for a 
DeployableContainer implementor.

John Ament says at https://github.com/wildfly/wildfly-arquillian/issues/116 with "Containers probably still need to do something to support this feature."  but it can be shown that this is just not possible with the current arquillian-core implementation and interfaces.

We need to remove the testable=true parameters from ShouldThrows for the TCK to be valid
for Container Implementations with the current Arquillian architecture/interfaces any contradiction of this can be logically shown to be false. 

One can see the gist by looking at:
https://github.com/arquillian/arquillian-core/blob/master/container/spi/src/main/java/org/jboss/arquillian/container/spi/client/container/DeployableContainer.java

@johnament  ?
@McFoggy  ?

@Emily can we please remove the ",testable=true" string from the ShouldThrowExceptions in
the TCK?

**Comment by hutchig** [comment] 2018-05-14 14:42
Hi @carlosdlr, thanks but I have done the PR already #277 :-)

**Comment by hutchig** [comment] 2018-05-14 17:04
Indeed (and for those not familiar with the thread - @Azquelts workaround
was an alternative hook to get an extension to be run for a non-deployable
artifact - not a way to get ShouldThrowException(.... testable=true) to
work for a DeployableContainer - which is impossible. )

**Comment by hutchig** [comment] 2018-05-15 14:26
Hi @McFoggy not sure if it is the @BeforeDeploy annotation (which would need
a change in the test program) or actually the use of a loadable extension.

If it was me I would do something like a
https://github.com/arquillian/arquillian-showcase/blob/68bd3d651fe675ed0b755e67295f8960c5cce92b/extensions/lifecycle/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension#L1
 
and then implement the method here: 

the https://github.com/arquillian/arquillian-showcase/blob/68bd3d651fe675ed0b755e67295f8960c5cce92b/extensions/lifecycle/src/main/java/org/jboss/arquillian/showcase/extension/lifecycle/LifecycleExecuter.java#L38

We use a loadable extension currently in the Liberty Config TCK runner to
add a jar (https://github.com/OpenLiberty/open-liberty/blob/7b4b4e78463b44ecd050cbc49b565e1c8c282ab0/dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension#L1) and it works reliabely, albeit to
register a extensionBuilder.service and not a LifecycleExecuter.

**Comment by hutchig** [comment] 2018-05-21 10:33
This issue is now not there and it should be closed - unless @Emily-Jiang you know something I don't?

**Comment by Emily-Jiang** [comment] 2018-05-21 10:37
Should we open a new issue to log your suggestions?

**Comment by hutchig** [comment] 2018-05-21 10:39
I think the suggestions are vendor specific - so probably not appropriate for the general issue list.

**Comment by Emily-Jiang** [comment] 2018-05-21 10:47
Let's close it for now.

**Closed by Emily-Jiang** 2018-05-21 10:47 UTC
